# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [ push, pull_request ]

permissions:
  checks: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
          fail_on_error: true
          level: warning
          reviewdog_flags: -name="gradle" -reporter=github-check -filter-mode=nofilter -fail-on-error -level=warning

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/test-results/**/TEST-*.xml"
        if: always()

#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        with:
#          junit_files: 'build/test-results/**/TEST-*.xml'
#        if: always()

#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v3
#        if: success() || failure() # always run even if the previous step fails
#        with:
#          report_paths: 'build/test-results/**/TEST-*.xml'

